// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plulkcunxqjyvsbwgziy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdWxrY3VueHFqeXZzYndneml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTY1NTIsImV4cCI6MjA2ODIzMjU1Mn0.aejkAn1S9TL5lPU7ntNKmbZkkvN4fHPXVTZUGQhwIJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});